# Generated by Django 5.1.1 on 2024-09-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('rent', 'Rent'), ('entertainment', 'Entertainment'), ('utilities', 'Utilities'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.CharField(choices=[('salary', 'Salary'), ('freelance', 'Freelance'), ('investments', 'Investments'), ('gifts', 'Gifts'), ('other', 'Other')], max_length=40),
        ),
    ]
